version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
  pre_build:
    commands:
      - echo "=== pre_build 시작 ==="
      - cd FrontEnd/frontend && npm install && cd ../../
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 879772956301.dkr.ecr.us-east-1.amazonaws.com
      - aws eks update-kubeconfig --region us-east-1 --name $ACCOUNT-cluster
  build:
    commands:
      - cd FrontEnd/frontend && npm run build && cd ../../
      - cd BackEnd && chmod +x ./gradlew && ./gradlew clean build -x test && cd ..
      - docker build -t team18-dev5-backend ./BackEnd
      - docker tag team18-dev5-backend:latest 879772956301.dkr.ecr.us-east-1.amazonaws.com/team18-dev5-backend:latest
  post_build:
    commands:
      - docker push 879772956301.dkr.ecr.us-east-1.amazonaws.com/team18-dev5-backend:latest
      - aws s3 sync $CODEBUILD_SRC_DIR/FrontEnd/frontend/dist s3://team18-dev5-website --delete
      - kubectl apply -f BackEnd/k8s/

artifacts:
  files:
    - BackEnd/build/libs/*.jar
    - FrontEnd/frontend/dist/**/*
  discard-paths: no