apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 879772956301.dkr.ecr.us-east-1.amazonaws.com/team18-dev5-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        - name: CORS_ORIGIN
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: CORS_ORIGIN
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: ADMIN_PASSWORD