version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    EKS_CLUSTER_NAME: user135-cluster
    BACKEND_ECR_URI: 879772956301.dkr.ecr.us-east-1.amazonaws.com/team18-backend
    FRONTEND_ECR_URI: 879772956301.dkr.ecr.us-east-1.amazonaws.com/team18-frontend
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME

  build:
    commands:
      - echo Replacing backend image URI
      - sed -i "s|BACKEND_IMAGE_URI_PLACEHOLDER|$BACKEND_ECR_URI:$IMAGE_TAG|g" k8s/backend-deployment.yaml

      - echo Replacing frontend image URI
      - sed -i "s|FRONTEND_IMAGE_URI_PLACEHOLDER|$FRONTEND_ECR_URI:$IMAGE_TAG|g" k8s/frontend-deployment.yaml

      - echo Applying backend manifests
      - kubectl apply -f k8s/backend-deployment.yaml
      - kubectl apply -f k8s/backend-service.yaml

      - echo Applying frontend manifests
      - kubectl apply -f k8s/frontend-deployment.yaml
      - kubectl apply -f k8s/frontend-service.yaml

  post_build:
    commands:
      - echo Checking backend rollout
      - kubectl rollout status deployment/bookapp-backend

      - echo Checking frontend rollout
      - kubectl rollout status deployment/bookapp-frontend