version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
  pre_build:
    commands:
      - echo Build started on `date`
      - cd FrontEnd/frontend && npm install && cd ../../
  build:
    commands:
      - cd FrontEnd/frontend && npm run build && cd ../../
      - cd BackEnd && chmod +x ./gradlew && ./gradlew clean build -x test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - BackEnd/build/libs/*.jar
    - FrontEnd/frontend/dist/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no