version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Check source root"
      - pwd
      - ls -al
      - ls -al BackEnd
      - chmod +x BackEnd/gradlew

  build:
    commands:
      - echo "Build Spring Boot backend"
      - cd BackEnd && ./gradlew clean build -x test
      - echo "Build Completed."

  post_build:
    commands:
      - echo "Prepare deployment files"
      - mkdir -p build-output
      - cp BackEnd/build/libs/*.jar build-output/
      - cp BackEnd/appspec.yml build-output/
      - cp -r BackEnd/deploy-scripts build-output/

artifacts:
  base-directory: build-output
  files:
    - '**/*'