version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Prepare backend build"
      - pwd
      - ls -al
      - chmod +x gradlew
  build:
    commands:
      - echo "Build Spring Boot backend"
      - ./gradlew clean build -x test
      - echo "Build Completed."
  post_build:
    commands:
      - echo "Prepare deployment files"
      - mkdir -p build-output
      - cp build/libs/*.jar build-output/
      - cp appspec.yml build-output/
      - cp -r deploy-scripts build-output/
artifacts:
  base-directory: build-output
  files:
    - '**/*'